version: 2

sources:
  - name: "{{ var('raw_database') }}"
    description: "Database of ethereum raw"
    database: "{{ var('raw_database') }}"
    schema: raw
    tables:
      - name: transactions
        description: "ethereum raw transactions"
        identifier: "{{ var('source_table_transactions') }}"
      - name: logs
        description: "ethereum raw logs"
        identifier: "{{ var('source_table_logs') }}"
      - name: traces
        description: "ethereum raw traces"
        identifier: "{{ var('source_table_traces') }}"
      - name: blocks
        description: "ethereum raw blocks"
        identifier: "{{ var('source_table_blocks') }}"
  - name: "{{ var('contracts_database') }}"
    description: "Database of ethereum contract info, including event fragments and method fragments"
    database: "{{ var('contracts_database') }}"
    schema: evm
    tables:
      - name: method_fragments
        description: "table of method fragments"
      - name: event_fragments
        description: "table of event fragments"