version: 2

sources:
  - name: ethereum_raw_data
    description: "Database of ethereum raw"
    database: ethereum_raw_data
    schema: raw
    tables:
      - name: transactions
        description: "ethereum raw transactions"
      - name: logs
        description: "ethereum raw logs"
      - name: traces
        description: "ethereum raw traces"
      - name: blocks
        description: "ethereum raw blocks"
  - name: evm_contract_fragments_data
    description: "Database of ethereum contract info, including event fragments and method fragments"
    database: evm_contract_fragments_data
    schema: evm
    tables:
      - name: method_fragments
        description: "table of method fragments"
      - name: event_fragments
        description: "table of event fragments"